### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by JaZo** [modprobe/phpstan-bitbucket#1]
Hi @modprobe, this formatter is really nice! But unfortunately my employer's policy doesn't allow usage of unlicensed packages. Will you consider adding a license? Maybe we can also improve the package and update PHP compatibility, adding a readme, etc. Please let me know!

**Comment by modprobe** [comment]
Hi @JaZo! I wrote this on a whim but it never ended up being useful for me, hence the sorry state of affairs 😄 

I've licensed it under MIT. If you want to make improvements, I'm very happy to accept PR's, or feel free to fork it.

**Comment by JaZo** [comment]
Thanks for the speedy reply and action!
